# Generated by Django 5.0.6 on 2024-05-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "company_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "simulation_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("simulation_name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_surname", models.CharField(max_length=255)),
                ("signup_datetime", models.DateTimeField()),
                ("progress_percent", models.FloatField()),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.simulation",
                    ),
                ),
            ],
        ),
    ]
